$destRoot = "C:\Users\nd115232\Documents\GitHub\dima-publishing\books\database-book\files\source\chapters"

function Update-Index($chFolder, $chNum, $title, $desc) {
    $dir = Join-Path $destRoot $chFolder
    $files = Get-ChildItem $dir -File | Where-Object { $_.Name -match "^(ch$chNum|lab-$chNum)-.*-\d{4}-\d{2}-\d{2}\.md$" } | Sort-Object Name
    
    $mainFile = $files | Where-Object Name -match "^ch$chNum-main-" | Select-Object -First 1
    $lbFile = $files | Where-Object Name -match "^ch$chNum-lets-build-" | Select-Object -First 1
    $reflFile = $files | Where-Object Name -match "^ch$chNum-reflection-" | Select-Object -First 1
    $termsFile = $files | Where-Object Name -match "^ch$chNum-terms-" | Select-Object -First 1
    $ratFile = $files | Where-Object Name -match "^ch$chNum-rat-" | Select-Object -First 1
    $labFile = $files | Where-Object Name -match "^lab-$chNum-questions-" | Select-Object -First 1
    
    $chNumInt = [int]$chNum
    
    $index = "# Chapter $chNumInt`: $title`n`n$desc`n`n## Chapter Files`n`n"
    if ($mainFile) { $index += "- [Main Chapter]($($mainFile.Name))`n" }
    if ($lbFile) { $index += "- [Let's Build]($($lbFile.Name))`n" }
    if ($reflFile) { $index += "- [Review & Reflection]($($reflFile.Name))`n" }
    if ($termsFile) { $index += "- [Terms Treasury]($($termsFile.Name))`n" }
    if ($ratFile) { $index += "- [Readiness Assessment Test]($($ratFile.Name))`n" }
    if ($labFile) { 
        $index += "`n## Lab`n`n- [Lab $chNumInt Questions]($($labFile.Name))`n" 
    }
    $index += "`n---`n*Generated by chapter-sync on $(Get-Date -Format 'yyyy-MM-dd')*`n"
    
    $idxPath = Join-Path $dir "index.md"
    [System.IO.File]::WriteAllText($idxPath, $index, [System.Text.UTF8Encoding]::new($false))
    Write-Output "REGEN: $chFolder/index.md"
}

# ch01
$desc01 = "This chapter orients you to the textbook, its instructional approach, the PetVax project, and the tools you will use throughout the course."
Update-Index "ch01-introduction-to-course" "01" "Introduction to the Course" $desc01

# ch05
$desc05 = "SQL is the language of databases. This chapter introduces SELECT, WHERE, ORDER BY, aggregation, GROUP BY, and JOIN queries with hands-on practice in the Grading Database."
Update-Index "ch05-sql" "05" "SQL" $desc05
